# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 21:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AuthorName', models.CharField(max_length=50)),
                ('AuthorBio', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookName', models.CharField(max_length=50, null=True)),
                ('BookDateOfPublish', models.DateField(blank=True, null=True)),
                ('BookImage', models.ImageField(blank=True, null=True, upload_to='')),
                ('BookPageCount', models.IntegerField(null=True)),
                ('BookSummary', models.TextField(blank=True, max_length=1000)),
                ('BookRatesCount', models.IntegerField(blank=True, default=0, editable=False)),
                ('BookRatesSum', models.IntegerField(blank=True, default=0, editable=False)),
                ('BookAuthor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Book.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('CommentOnBook', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Book.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PublisherName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(choices=[(5, 'Excellent'), (4, 'Good'), (3, 'Not Bad'), (2, 'Bad'), (1, 'Awful')])),
            ],
        ),
        migrations.CreateModel(
            name='Translator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TranslatorName', models.CharField(max_length=50)),
                ('TranslatorBio', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='BookComments',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='Book.Comment'),
        ),
        migrations.AddField(
            model_name='book',
            name='BookPublisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Book.Publisher'),
        ),
        migrations.AddField(
            model_name='book',
            name='BookTranslator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Book.Translator'),
        ),
    ]
