# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='PublisherBooks',
        ),
        migrations.AddField(
            model_name='publisher',
            name='PublisherBooks',
            field=models.ManyToManyField(null=True, related_name='PublisherBooks', to='Book.Book'),
        ),
    ]
