# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 19:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0002_auto_20171019_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='BookAuthor',
        ),
        migrations.RemoveField(
            model_name='book',
            name='BookPublisher',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='PublisherBooks',
        ),
        migrations.AddField(
            model_name='publisher',
            name='PublisherBooks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PublisherBooks', to='Book.Book'),
        ),
    ]
