# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 15:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Book', '0003_auto_20171101_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='UsersReadThisBook',
        ),
        migrations.AddField(
            model_name='book',
            name='UsersReadThisBook',
            field=models.ManyToManyField(blank=True, null=True, related_name='Reads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='book',
            name='UsersReadingThisBook',
        ),
        migrations.AddField(
            model_name='book',
            name='UsersReadingThisBook',
            field=models.ManyToManyField(blank=True, null=True, related_name='Readings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='book',
            name='UsersWantsToReadThisBook',
        ),
        migrations.AddField(
            model_name='book',
            name='UsersWantsToReadThisBook',
            field=models.ManyToManyField(blank=True, null=True, related_name='toReads', to=settings.AUTH_USER_MODEL),
        ),
    ]
