# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 16:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0003_auto_20171004_1654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='authorName',
            new_name='AuthorName',
        ),
    ]
