# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 15:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0004_auto_20171101_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='UsersReadThisBook',
        ),
        migrations.RemoveField(
            model_name='book',
            name='UsersReadingThisBook',
        ),
        migrations.RemoveField(
            model_name='book',
            name='UsersWantsToReadThisBook',
        ),
    ]
