# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0005_auto_20171019_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='BookPublisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Book.Publisher'),
        ),
    ]
