# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-10 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0006_auto_20171004_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='BookCommentsCount',
        ),
        migrations.AddField(
            model_name='comment',
            name='CommentOnBook',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Book.Book'),
        ),
    ]
