# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0006_auto_20171019_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='PublisherBooks',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PublisherBooks', to='Book.Book'),
        ),
    ]
