# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-10 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0007_auto_20171010_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='BookTranslator',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Book.Translator'),
        ),
    ]
