# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0007_auto_20171019_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='AuthorBooks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AuthorBooks', to='Book.Book'),
        ),
    ]
