# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-10 20:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0008_auto_20171010_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='BookAuthor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Book.Author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='BookPublisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Book.Publisher'),
        ),
        migrations.AlterField(
            model_name='book',
            name='BookTranslator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Book.Translator'),
        ),
    ]
