# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 14:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0008_author_authorbooks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='BookPublisher',
        ),
    ]
