# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0010_auto_20171021_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='PublisherBooks',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PublisherBooks', to='Book.Book'),
        ),
    ]
