# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0011_publisher_publisherbooks'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='BookComments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Book.Comment'),
        ),
        migrations.AddField(
            model_name='book',
            name='BookRatesCount',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='BookRatesSum',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
