# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0012_auto_20171021_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='BookAuthor',
        ),
        migrations.RemoveField(
            model_name='book',
            name='BookPublisher',
        ),
        migrations.AlterField(
            model_name='book',
            name='BookComments',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='Book.Comment'),
        ),
        migrations.AlterField(
            model_name='book',
            name='BookRatesCount',
            field=models.IntegerField(blank=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='BookRatesSum',
            field=models.IntegerField(blank=True, default=0, editable=False),
        ),
    ]
