# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 15:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0014_auto_20171021_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='BookAuthor',
        ),
        migrations.RemoveField(
            model_name='book',
            name='BookPublisher',
        ),
        migrations.RemoveField(
            model_name='book',
            name='BookTranslator',
        ),
    ]
