# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 07:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0015_auto_20171021_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='BookPublisher',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Book.Publisher'),
        ),
    ]
