# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0016_book_bookpublisher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='BookPublisher',
        ),
        migrations.AddField(
            model_name='book',
            name='BookPublisher',
            field=models.ManyToManyField(null=True, to='Book.Publisher'),
        ),
    ]
