# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 07:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0017_auto_20171026_0717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='BookPublisher',
        ),
        migrations.AddField(
            model_name='book',
            name='BookPublisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Book.Publisher'),
        ),
    ]
