# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 19:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0019_remove_publisher_publisherbooks'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='BookAuthor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Book.Author'),
        ),
        migrations.AddField(
            model_name='book',
            name='BookTranslator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Book.Translator'),
        ),
    ]
