# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 19:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0021_book_bookpagecount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='AuthorBooks',
        ),
    ]
