# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('Book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.Profile'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='books',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Book.Book'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.Profile'),
        ),
        migrations.AddField(
            model_name='book',
            name='BookAuthor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Book.Author'),
        ),
        migrations.AddField(
            model_name='book',
            name='BookComments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Book.Comment'),
        ),
        migrations.AddField(
            model_name='book',
            name='BookPublisher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Book.Publisher'),
        ),
        migrations.AddField(
            model_name='book',
            name='BookTranslator',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Book.Translator'),
        ),
        migrations.AddField(
            model_name='author',
            name='books',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Book.Book'),
        ),
    ]
