# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 16:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0002_auto_20171004_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='books',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='books',
        ),
        migrations.RemoveField(
            model_name='translator',
            name='books',
        ),
    ]
