# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='url',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
