# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 21:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='shelves',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Shelf'),
        ),
    ]
