# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20171101_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Read',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Read', to='Book.Book', unique=True),
        ),
    ]
