# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 21:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='token',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authtoken.Token'),
        ),
    ]
