# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 08:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20171114_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='token',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='authtoken.Token'),
        ),
    ]
