# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 13:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0010_auto_20171017_1301'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0003_auto_20171017_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('family_name', models.CharField(max_length=30)),
                ('birth_date', models.DateField(blank=True)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('phone_number', models.IntegerField(blank=True)),
                ('avatar', models.ImageField(blank=True, upload_to='avatars')),
                ('location', models.CharField(blank=True, max_length=30)),
                ('user_type', models.CharField(choices=[('SU', 'Super User'), ('U', 'User')], default='U', max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='books',
        ),
        migrations.RemoveField(
            model_name='user',
            name='django_user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='profile',
            name='django_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
