# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20171101_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Read',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Reading',
        ),
        migrations.RemoveField(
            model_name='user',
            name='toRead',
        ),
    ]
