# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0003_auto_20171101_1408'),
        ('user', '0006_auto_20171101_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Read',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Read', to='Book.Book'),
        ),
    ]
