# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0004_auto_20171101_1507'),
        ('user', '0007_user_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Read',
        ),
        migrations.AddField(
            model_name='user',
            name='Read',
            field=models.ManyToManyField(blank=True, null=True, related_name='Read', to='Book.Book'),
        ),
    ]
