# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20171101_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Reading',
            new_name='Readings',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='toRead',
            new_name='toReads',
        ),
    ]
