# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0005_auto_20171101_1536'),
        ('user', '0011_auto_20171101_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Readings',
        ),
        migrations.AddField(
            model_name='user',
            name='Readings',
            field=models.ManyToManyField(blank=True, null=True, related_name='Reading', to='Book.Book'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='toReads',
        ),
        migrations.AddField(
            model_name='user',
            name='toReads',
            field=models.ManyToManyField(blank=True, null=True, related_name='toRead', to='Book.Book'),
        ),
    ]
